name: Release Workflow

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  REGISTRY_PATH: ${{ secrets.ORG_AZURE_DOCKER_REGISTRY_LOGIN_SERVER_DEV }}
  IMAGE_NAME: pymupdf-service/pymupdf-service
  DOCKERFILE_PATH: ./devops/Dockerfile
  BUILD_INFO_PATH: ./build.info

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get-version
        run: |
          if [ -f "${{ env.BUILD_INFO_PATH }}" ]; then
            version=$(cat ${{ env.BUILD_INFO_PATH }})
          else
            version="$(date +'%Y.%m.%d')-${GITHUB_RUN_NUMBER}"
          fi
          echo "version=$version" >> "$GITHUB_OUTPUT"

  build-and-release:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_PATH }}
          username: ${{ secrets.ORG_AZURE_DOCKER_REGISTRY_USERNAME_DEV }}
          password: ${{ secrets.ORG_AZURE_DOCKER_REGISTRY_LOGIN_PASSWORD_DEV }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ needs.get-version.outputs.version }}
            ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:latest

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.get-version.outputs.version }}
          release_name: Release ${{ needs.get-version.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Docker Image:
            - ${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ needs.get-version.outputs.version }}